import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { eq } from "drizzle-orm";
import { getDb } from "../db/client";
import { users } from "../db/schema";

export function createAuth(env: any) {
  const db = getDb(env);

  return betterAuth({
    database: drizzleAdapter(db, {
      provider: "pg",
      // Our schema exports plural table names (users, sessions, accounts,
      // verifications), so the adapter must be told to look up plural model
      // names or it will fail to find any of the auth tables.
      usePlural: true,
    }),
    advanced: {
      database: {
        // users.id/sessions.id/etc. are Postgres `serial` (numeric) primary
        // keys, not Better Auth's default string ids, so ids must come from
        // the database's auto-increment rather than being generated by us.
        generateId: "serial",
      },
    },
    secret: env.BETTER_AUTH_SECRET,
  });
}

export async function requireUser(ctx: { env: any; request: Request }) {
  const auth = createAuth(ctx.env);
  const session = await auth.api.getSession({ headers: ctx.request.headers });

  if (!session?.user?.email) {
    return null;
  }

  // Treat the database as the source of truth for user data (e.g. isAdmin)
  // instead of trusting whatever fields happen to be present on the session
  // payload.
  const db = getDb(ctx.env);
  const dbUser = await db.query.users.findFirst({
    where: eq(users.email, session.user.email),
  });

  return dbUser ?? null;
}

export async function requireAdminUser(ctx: { env: any; request: Request }) {
  if (ctx.env.DEV_USER_EMAIL) {
    console.warn(`AUTH BYPASS: Forcibly logging in as ${ctx.env.DEV_USER_EMAIL}`);

    const db = getDb(ctx.env);
    const devUser = await db.query.users.findFirst({
      where: eq(users.email, ctx.env.DEV_USER_EMAIL),
    });

    if (!devUser) {
      throw new Error(`DEV BYPASS FAILED: User ${ctx.env.DEV_USER_EMAIL} not found in DB.`);
    }

    if (devUser.isAdmin !== true) {
      throw new Error(`DEV BYPASS ERROR: User ${devUser.email} is not an admin.`);
    }

    return devUser;
  }

  const user = await requireUser(ctx);

  if (!user) {
    throw new Error("You must be logged in.");
  }

  if (user.isAdmin !== true) {
    throw new Error("You do not have permission to access this resource.");
  }

  return user;
}
